version: '3.8'

services:
  viveye:
    build: .
    ports:
      - "5000:5000"
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./tor-data:/app/tor-data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - viveye-network

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    networks:
      - viveye-network

volumes:
  mongodb_data:

networks:
  viveye-network:
    driver: bridge
